### ISSUE TITLE
SmartServoGui "serial not found"

### ISSUE THREAD

**Issue by elthef** [emericg/SmartServoFramework#22]
I used to be able to run the smart gui program to access the data from the 0402 servo.
However, recently I encountered serial not found problem. Any suggestion ?
Thank you

**Comment by emericg** [comment]
Hi,
can you detail what was working before (OS, version of the software) and what changed now that it's not working?

Thanks

**Comment by elthef** [comment]
I am working in Ubuntu 16.04 LTS xenial,
Qmake version 3.0
Using QT 5.5.1
The smart GUI interface can  start SmartServoGui but under the San fro new serial poer it reported no serial port.
I have already chmod +x for /dev/ttyUSB0

Edwin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by emericg** [comment]
Hey,
You really should add your user instead of chmoding the serial port device, it will not be enough. The serial port not showing up at all is usually a good sign of just not having permissions to access the device.
> usermod -a -G uucp,dialout $USER

Between the moment where it was working and now, did you changed the version of SmartServoGui, of your serial adapter, or anything?

**Comment by elthef** [comment]
I managed to rectify the problem. It seems that I need to uninstall QT5 and reinstall QT4 then recompile the program and it works
